---
- name: EC2
  hosts: localhost

  tasks:
  - name: create EC2
    amazon.aws.ec2_instance:
      instance_type: t3.small
      image_id: ami-0e731c8a588258d0d
      count: 1
      region: us-east-2
     # network:
     #   assign_public_ip: true
     #   security_group: default
     #   vpc_subnet_id: subnet-0123456
      state: present
      tags:
        foo: bar
