---
- name: EC2
  hosts: localhost

  tasks:
  - name: create EC2
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      image_id: ami-0c20d88b0021158c6
      count: 1
      region: us-east-2
     # network:
     #   assign_public_ip: true
     #   security_group: default
     #   vpc_subnet_id: subnet-0123456
      state: present
      tags:
        foo: bar
