---
- name: EC2
  hosts: localhost
  vars:
    name: test2
    instancetype: t2.micro
    imageid: ami-0c20d88b0021158c6
    counts: 1
    ec2region: us-east-2
    iam_role: EC2SSM
    
  tasks:
  - name: restart a particular instance by its ID
    amazon.aws.ec2_instance:
      state: absent
      region: "{{ ec2region }}"

       
